# Generated by Django 5.1.5 on 2025-02-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bands/'),
        ),
    ]
