# Generated by Django 5.1.2 on 2025-02-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_booking_payment_status_booking_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='transaction_id',
        ),
    ]
