# Generated by Django 5.1.2 on 2025-03-03 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_buy2_order2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy2',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order2'),
        ),
    ]
