# Generated by Django 5.1.2 on 2025-03-03 05:01

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_buy2_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy2',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name=app.models.Booking),
        ),
    ]
