# Generated by Django 5.1.5 on 2025-02-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='material',
        ),
        migrations.RemoveField(
            model_name='products',
            name='weight',
        ),
    ]
